import { Practitioner } from "./types";

export const practitioners: Practitioner[] = [
  {
    id: "emily-watson",
    name: "Emily Watson",
    title: "Advanced Aesthetic Nurse Prescriber",
    specialisms: ["Anti-Wrinkle Injections", "Dermal Fillers", "Skin Boosters"],
    location: "Manchester",
    region: "North West",
    tier: "premium",
    bio: "Founder-level injector with a decade of NHS and private aesthetics experience, specialising in natural-looking facial balancing.\n\nEmily started her career in NHS plastic surgery before moving into full-time aesthetics, and built her training programme around the same complication-first mindset she learned on the ward. Her courses run in small cohorts so every delegate gets hands-on injecting time, not just observation.\n\nShe is regularly invited to speak at UK aesthetics conferences on facial anatomy and patient safety, and several of her former trainees now run their own clinics across the North West.",
    yearsExperience: 11,
    initials: "EW",
  },
  {
    id: "sarah-okafor",
    name: "Sarah Okafor",
    title: "Aesthetic Practitioner & Trainer",
    specialisms: ["PDO Threads", "Dermal Fillers", "Profhilo"],
    location: "Liverpool",
    region: "North West",
    tier: "premium",
    bio: "Award-winning trainer focused on thread lifting and skin laxity treatments, regularly featured in industry panels.\n\nSarah trained originally as a beauty therapist before moving into medical aesthetics, which gives her teaching a strong focus on skin assessment and managing client expectations alongside the technical injecting skills. Her thread lift modules are some of the most requested on the Hub.\n\nShe keeps her course sizes deliberately small and offers free phone support to every delegate for the first month after training, something she says has made the biggest difference to her trainees' confidence.",
    yearsExperience: 8,
    initials: "SO",
  },
  {
    id: "james-whitfield",
    name: "James Whitfield",
    title: "Cosmetic Doctor",
    specialisms: ["Anti-Wrinkle Injections", "Fat Dissolving Injections", "Chemical Peels"],
    location: "London",
    region: "Greater London",
    tier: "premium",
    bio: "GMC-registered doctor delivering CPD-accredited masterclasses on injectable safety and complication management.\n\nBefore moving into aesthetics, James worked for several years in emergency medicine, which shapes the way he teaches complication recognition and management — a topic he feels is too often glossed over in foundation training. His masterclasses combine theory with live model demonstrations.\n\nHe also runs a monthly clinical governance session for past trainees, covering case studies and updates to best practice guidance from the relevant UK regulatory bodies.",
    yearsExperience: 14,
    initials: "JW",
  },
  {
    id: "priya-natarajan",
    name: "Priya Natarajan",
    title: "Aesthetic Nurse Prescriber",
    specialisms: ["Lip Filler", "Skin Boosters", "Microneedling"],
    location: "Birmingham",
    region: "West Midlands",
    tier: "premium",
    bio: "Specialist in lip enhancement and skin quality treatments, known for a meticulous, education-first teaching style.\n\nPriya's background is in dermatology nursing, and she brings that clinical rigour into every course — delegates leave with a structured framework for lip assessment, not just a set of injection points to memorise. She is particularly known for her work on natural-looking results for first-time filler clients.\n\nHer Birmingham training suite is fully equipped for both teaching and live model days, and she partners with a local skin clinic so trainees can see real consultations before they start treating.",
    yearsExperience: 9,
    initials: "PN",
  },
  {
    id: "tom-fielding",
    name: "Tom Fielding",
    title: "Aesthetic Practitioner",
    specialisms: ["Anti-Wrinkle Injections", "Dermal Fillers"],
    location: "Leeds",
    region: "Yorkshire",
    tier: "standard",
    bio: "Former dental nurse turned full-time injector, teaching foundation-level injectable courses for new practitioners.\n\nTom focuses specifically on practitioners taking their very first injectable course, and structures his day around getting people comfortable with needles and cannulas before moving on to technique — something he wishes more foundation courses prioritised when he was starting out.",
    yearsExperience: 5,
    initials: "TF",
  },
  {
    id: "amara-chukwu",
    name: "Amara Chukwu",
    title: "Aesthetic Nurse",
    specialisms: ["Chemical Peels", "Microneedling", "Skin Boosters"],
    location: "Bristol",
    region: "South West",
    tier: "standard",
    bio: "Runs hands-on skin treatment workshops with a focus on acne scarring and pigmentation correction.\n\nHaving spent years treating her own clients with stubborn pigmentation and scarring, Amara built her course around the case types that actually walk into a clinic, rather than textbook examples. Each workshop includes real before-and-after case reviews from her own practice.",
    yearsExperience: 4,
    initials: "AC",
  },
  {
    id: "ryan-mcleod",
    name: "Ryan McLeod",
    title: "Aesthetic Practitioner & Trainer",
    specialisms: ["PRP Hair Restoration", "Laser Hair Removal"],
    location: "Edinburgh",
    region: "Scotland",
    tier: "standard",
    bio: "One of Scotland's few dedicated hair restoration trainers, covering PRP protocols and patient selection.\n\nRyan moved into hair restoration after noticing how underserved the category was compared to facial aesthetics, and now runs one of the only dedicated PRP and laser hair removal courses north of the border. His training covers patient selection and realistic outcome-setting as much as the procedures themselves.",
    yearsExperience: 6,
    initials: "RM",
  },
  {
    id: "hannah-doyle",
    name: "Hannah Doyle",
    title: "Aesthetic Nurse Prescriber",
    specialisms: ["Dermal Fillers", "Anti-Wrinkle Injections", "Profhilo"],
    location: "Newcastle",
    region: "North East",
    tier: "standard",
    bio: "Teaches small-group facial assessment courses with an emphasis on consent and complication protocols.\n\nHannah caps every course at four delegates so she can give individual feedback on facial assessment technique, which she sees as the skill most new practitioners under-practise. Consent and complication protocols are covered on day one, not as an afterthought.",
    yearsExperience: 7,
    initials: "HD",
  },
  {
    id: "leon-marsh",
    name: "Leon Marsh",
    title: "Aesthetic Practitioner",
    specialisms: ["Fat Dissolving Injections", "PDO Threads"],
    location: "Cardiff",
    region: "Wales",
    tier: "standard",
    bio: "Body contouring specialist offering practical, small-cohort training days for working practitioners.\n\nLeon's training days are built for practitioners already working in clinic who want to add body contouring to their offering, with an emphasis on practical session structure and pricing as well as injection technique.",
    yearsExperience: 5,
    initials: "LM",
  },
  {
    id: "freya-armstrong",
    name: "Freya Armstrong",
    title: "Aesthetic Nurse",
    specialisms: ["Skin Boosters", "Lip Filler", "Microneedling"],
    location: "Nottingham",
    region: "East Midlands",
    tier: "standard",
    bio: "Focuses on conservative, skin-first treatment philosophy, popular with practitioners new to injectables.\n\nFreya's approach is built around a \"skin first\" philosophy — encouraging trainees to assess and treat skin quality before reaching for filler. It's a popular starting point for practitioners who want a more conservative, less volume-led approach to facial aesthetics.",
    yearsExperience: 3,
    initials: "FA",
  },
];

export const allSpecialisms: string[] = Array.from(
  new Set(practitioners.flatMap((p) => p.specialisms))
).sort();

export const allLocations: string[] = Array.from(
  new Set(practitioners.map((p) => p.location))
).sort();
